# NOTE: this file was generated by the Mobile NixOS installer.
{ config, lib, pkgs, ... }:

{
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/5c011738-f598-4ebd-ac36-167de8cbd20d";
      fsType = "ext4";
    };
  };
  
  boot.initrd.luks.devices = {
    "LUKS-MARVIN-ROOTFS" = {
      device = "/dev/disk/by-uuid/2d5265de-705e-4da2-904c-7de0e975be64";
    };
  };

  nix.settings.max-jobs = lib.mkDefault 3;

  # Do NOT set hostPlatform here, because it breaks mobile-nixos
  # https://github.com/NixOS/mobile-nixos/issues/564
  # nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
  nixpkgs.system = lib.mkDefault "aarch64-linux";
}
