# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

	boot = {
		initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
		initrd.kernelModules = [ ];

		# acpi_call is needed for tlp to work properly on the thinkpad
		kernelModules = [ "kvm-intel" "acpi_call" ];

		kernelParams = [
			# Disable "Panel Self Refresh".  Fix random freezes on the X270.
			"i915.enable_psr=0"
		];
		extraModulePackages = with config.boot.kernelPackages; [
			acpi_call
		];
	};

	fileSystems = {
		"/" = {
			device = "/dev/disk/by-uuid/8a13eb1e-ddfa-48ac-a5df-94f3f806f804";
			fsType = "ext4";
		};
		"/boot" = {
			device = "/dev/disk/by-uuid/1B70-CFE3";
			fsType = "vfat";
		};
	};
	boot.initrd.luks.devices."luks-37e66e63-a8bd-43c3-9148-a02cc71c5413".device = "/dev/disk/by-uuid/37e66e63-a8bd-43c3-9148-a02cc71c5413";
	swapDevices = [ { device = "/dev/disk/by-uuid/f3ae26c1-3fcc-41c4-aa31-377bef39223c"; } ];

	networking.useDHCP = lib.mkDefault true;
	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
	hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
