#!/bin/sh

function findcodeenv() {
	if [ -n "$1" ]; then
		# If they provided a directory then start there
		cd "$1" || exit $?
	fi

	local INITIAL_PWD=${PWD}

	while true; do
		if [ -f .code-env ]; then
			echo "${PWD}"
			cd "${INITIAL_PWD}"
			return 0
		fi

		cd .. || exit #?
		if [ "${PWD}" == "/" ]; then
			# No '.code-env' file was found, so fall back to using the current
			# dir. This means that no vim commands will be run, but we still
			# get a reattachable session.
			cd "${INITIAL_PWD}"
			echo "${PWD}"
			return 0
		fi
	done
}

if [ $# -gt 1 ]; then
	echo "Usage: code [<path>]"
	echo ""
	echo "If no path is specified then the current directory is used"
	exit 1
fi

ENV_DIR=$(findcodeenv $@)

NVIM_SESSION="${ENV_DIR}/.code-env"

# Change to the root of the environment, because the env file may have paths
# that are relative to that.
cd ${ENV_DIR}

SOCKET_DIR="${HOME}/.dtach-sockets/${ENV_DIR}"
mkdir -p "${SOCKET_DIR}"

if [ -f "${NVIM_SESSION}" ]; then
	dtach -A "${SOCKET_DIR}/dtach.socket" -z -r winch nvim -S "${NVIM_SESSION}"
else
	dtach -A "${SOCKET_DIR}/dtach.socket" -z -r winch nvim
fi


