#!/bin/sh

#!/bin/sh

# Output a value for the average CPU usage for the last x minutes, formatted
# in a way that can be used with a sparks font to show a nice little chart.
#
# The output is sent every x seconds, so it can easily be used with waybar

# The number of seconds to wait between each data point
delay=1

# The number of data points to keep
count=25

values[0]=0
for (( i = 0; i < $count; i++ )) ; {
	values[$i]=0
}

# The values need to be printed with a comma between them
IFS=","

# Grab the status for 'cpu' which is a combination of all cores
prevstats=$(awk '/cpu / {printf "%d %d\n", ($2 + $3 + $4 + $5), $5 }' /proc/stat)
sleep $delay

while true; do
	curstats=$(awk '/cpu / {printf "%d %d\n", ($2 + $3 + $4 + $5), $5 }' /proc/stat)

	curtotal=${curstats%% *}
	curidle=${curstats##* }

	oldtotal=${prevstats%% *}
	oldidle=${prevstats##* }

	total=$(($curtotal - $oldtotal))
	idle=$(($curidle - $oldidle))
	busy=$(($total - $idle))

	if [ $total -eq 0 ]; then
		per=0
	else
		per=$(( ( $busy * 100 ) / ( $total ) ))
	fi

	# Remove the oldest value, and add a new value to the end of the list
	values=( "${values[@]:1}" )
	values+=($per)

	echo -en "{\"text\": \"{${values[*]}}\", \"tooltip\":\"$per%\"}\n"

	prevstats="$curstats"
	sleep $delay
done
